name: decoupled
recipe: drupal10
config:
  php: '8.2'
  via: apache
  webroot: ./web
  database: mysql
  xdebug: true
env_file:
  - .lando.env
services:
  appserver:
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=appserver"
        DRUSH_OPTIONS_URI: "https://decoupled.lndo.site"
    build_as_root:
      - apt update -y && apt install -y apt-transport-https build-essential unzip
      - curl -sL https://deb.nodesource.com/setup_16.x | bash -
      - apt-get install -y nodejs
      - chown -R www-data /usr/lib/node_modules
      - chown -R www-data /usr/bin
    build:
      - composer install
  next:
    type: node:18
    port: 3000
    build_as_root:
      - apt update -y && apt install -y apt-transport-https build-essential unzip
    build:
      - cd next && npm install
  storybook:
    type: node:16
    port: 6006
    build_as_root:
      - apt update -y && apt install -y apt-transport-https build-essential unzip
proxy:
  appserver:
    - decoupled.lndo.site
  next:
    - next.decoupled.lndo.site:3000
  storybook:
    - storybook.decoupled.lndo.site:6006
tooling:
  drush:
    service: appserver
    cmd: /app/vendor/bin/drush --root=/app/web
  npm:
    service: appserver
  node:
    service: appserver
  npx:
    service: appserver
  next:
    service: next
    cmd: npm run dev
    dir: /app/next
  storybook:
    service: storybook
    cmd: npm run storybook
    dir: /app/next
